services:
  kaizen-api:
    depends_on:
      - postgres
    restart: on-failure
    env_file:
      - .env
    image: coderphonui/kaizen-api:latest
    ports:
      - "8082:8082"
    volumes:
      - ./user-data:/app/user-data
    environment:
      USERDATA_PROVIDER: jpa
  kaizen-app:
    image: coderphonui/kaizen-app:latest
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: production

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./user-data/index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
  postgres:
    env_file:
      - .env
    image: postgres:latest
    environment:
      POSTGRES_USER: ${JDBC_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_PASSWORD}
      POSTGRES_DB: kaizen
    volumes:
      - ./user-data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  index_data:
    driver: local
  backups:
    driver: local
  postgres_data:
    driver: local
networks:
  default:
    name: kaizen